name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  kitchen:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        recipe: [ "server", "client" ]
        platform: [ "debian-11", "debian-12", "ubuntu-2204", "ubuntu-2404" ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby  # latest stable release
          bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
      - name: Run Test Kitchen ${{ matrix.recipe }}-${{ matrix.platform }}
        run: bundle exec rake kitchen:${{ matrix.recipe }}-${{ matrix.platform }}
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby  # latest stable release
          bundler-cache: true  # runs 'bundle install' and caches installed gems automatically
      - name: Run style checks
        run: bundle exec rake style:ruby
